SELECT
  CASE
    WHEN ID % 2 != 0 AND COUNTS != ID THEN ID + 1
    WHEN ID % 2 != 0 AND COUNTS = ID THEN ID
    ELSE ID - 1
  END AS ID
 ,STUDENT
FROM
  SEAT AS S,
  (
    SELECT COUNT(*) AS COUNTS
    FROM SEAT
  ) AS SC
ORDER BY ID ASC;
